site_name: klub-ia

site_url: https://itssofiarce.github.io/klubia/
use_directory_urls: true

theme:
  name: shadcn
  show_title: true 
  show_stargazers: true 
  pygments_style: 
        light: blinds-light
        dark: gruvbox-dark
  icon: heroicons:rocket-launch 
  topbar_sections: false 
  order: 2 
  sidebar_title: Navigation title



# mkdocs.yml

markdown_extensions:
  - admonition
 # - attr_list to be used in the home page maybe?
  - codehilite
  - shadcn.extensions.echarts.alpha
  - pymdownx.blocks.details
  - toc:
      permalink: true 
      title: Tabla de contenidos 
      toc_depth: 3


plugins:
  - awesome-pages
  - search
  - excalidraw


